### ISSUE TITLE
Add song from Youtube to play on whiteboard

### ISSUE THREAD

**Issue by h-qu** [net-art-uchicago/collaborative-artware#36]
Enable players to choose a song to upload from YouTube. Once they uploaded a song,they must then click a button to play it.After this they have the option to pause, continue playing, and to upload a new song from Youtube. To do this you will be using YouTube APIs and following Nick's tutorial.

**Comment by navila-luna** [comment]
Currently have written out a drop down select bar but it does not function properly. I'm thinking we could also have another drop down bar for changing the background music.I have found this: [https://stackoverflow.com/questions/34696208/play-a-sound-on-image-click-in-html](https://stackoverflow.com/questions/34696208/play-a-sound-on-image-click-in-html) and I think if we modify it so that it only attaches sound to the function when the person has said they wanted to add sound. This is similar to what I have but mine is written in p5j

**Comment by navila-luna** [comment]
Added a drop-down menu that currently has two mp3 sounds I uploaded. When a user clicks on the option bar, they will have the option to play the sound, which automatically plays once clicked. I need to figure out how to attach a sound to a specific location

**Comment by navila-luna** [comment]
Since having players uploading their sounds and attach them to a brush is far more complex and requires the backends support, Nick and I have decided it's better to change the general idea of adding sound to the whiteboard. We have decided that the user can select whichever video they want from YouTube and have it appear in the whiteboard. This still enables users to interact with sound in the whiteboard and choose which sounds they want to have.  Another sprint issue would be to then hide the YouTube video behind the canvas in which people will be drawing on. This sprint would also most likely deal with  enabling participants to choose what background picture (a url link of the photo they chose from the internet) to have as the background. The default color of the canvas would be white.

**Comment by navila-luna** [comment]
Sound Feature is working. Currently have it so that people can upload a song from youtube, pause it, and upload a new song. Within the creation of this feature, I did not need include the other feature  " enabling participants to choose what background picture". This would most likely be another separate issue since it's not related to sound.
